common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('password_reset/', views.MyPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('change_password/', views.change_password, name='change_password'),
    # path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),
]



# path('login/url/', views.RequestLoginViaUrlView.as_view(template_name='common/request_login_via_url_form.html'), name='request_login_via_url'),
# path('login/<uidb64>/<token>/', views.login_via_url, name='login_via_url'),

# path('activate/<uidb64>/<token>/', views.activate, name='activate'),

neworld/urls.py
from django.urls import path

from .views import base_views, scripture_views, meditation_views, question_views, \
    answer_views, comment_views, vote_views, weeklybible_views, research_views, \
    goldmembership_views, customer_views, activity_views, gpt_views, gptanswer_views

app_name = 'neworld'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),

    # goldmembership_views.py
    path('goldmembership_guide/', goldmembership_views.goldmembership_guide, name='goldmembership_guide'),

    # scripture_views.py
    path('scripture/',
         scripture_views.scripture, name='scripture'),
    path('scripture/<int:scripture_id>/',
         scripture_views.daily_scripture, name='daily_scripture'),

    # meditation_views.py
    path('meditation/create/<int:scripture_id>/',
         meditation_views.meditation_create, name='meditation_create'),
    path('meditation/modify/<int:meditation_id>/',
         meditation_views.meditation_modify, name='meditation_modify'),
    path('meditation/delete/<int:meditation_id>/',
         meditation_views.meditation_delete, name='meditation_delete'),

    # question_views.py
    path('question/', question_views.question, name='question'),
    path('question/<int:question_id>/',
         question_views.detail, name='detail'),
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/customer/<int:customer_id>/',
         comment_views.comment_create_customer, name='comment_create_customer'),
    path('comment/modify/customer/<int:comment_id>/',
         comment_views.comment_modify_customer, name='comment_modify_customer'),
    path('comment/delete/customer/<int:comment_id>/',
         comment_views.comment_delete_customer, name='comment_delete_customer'),
    path('comment/create/activity/<int:activity_id>/',
         comment_views.comment_create_activity, name='comment_create_activity'),
    path('comment/modify/activity/<int:comment_id>/',
         comment_views.comment_modify_activity, name='comment_modify_activity'),
    path('comment/delete/activity/<int:comment_id>/',
         comment_views.comment_delete_activity, name='comment_delete_activity'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),
    path('comment/create/meditation/<int:meditation_id>/',
         comment_views.comment_create_meditation, name='comment_create_meditation'),
    path('comment/modify/meditation/<int:comment_id>/',
         comment_views.comment_modify_meditation, name='comment_modify_meditation'),
    path('comment/delete/meditation/<int:comment_id>/',
         comment_views.comment_delete_meditation, name='comment_delete_meditation'),
    path('comment/create/research/<int:research_id>/',
         comment_views.comment_create_research, name='comment_create_research'),
    path('comment/modify/research/<int:comment_id>/',
         comment_views.comment_modify_research, name='comment_modify_research'),
    path('comment/delete/research/<int:comment_id>/',
         comment_views.comment_delete_research, name='comment_delete_research'),

    path('comment/create/gpt/<int:gpt_id>/',
         comment_views.comment_create_gpt, name='comment_create_gpt'),
    path('comment/modify/gpt/<int:comment_id>/',
         comment_views.comment_modify_gpt, name='comment_modify_gpt'),
    path('comment/delete/gpt/<int:comment_id>/',
         comment_views.comment_delete_gpt, name='comment_delete_gpt'),
    path('comment/create/gptanswer/<int:gptanswer_id>/',
         comment_views.comment_create_gptanswer, name='comment_create_gptanswer'),
    path('comment/modify/gptanswer/<int:comment_id>/',
         comment_views.comment_modify_gptanswer, name='comment_modify_gptanswer'),
    path('comment/delete/gptanswer/<int:comment_id>/',
         comment_views.comment_delete_gptanswer, name='comment_delete_gptanswer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
    path('vote/scripture/<int:scripture_id>/', vote_views.vote_scripture, name='vote_scripture'),
    path('vote/meditation/<int:meditation_id>/', vote_views.vote_meditation, name='vote_meditation'),
    path('vote/weeklybible/<int:weeklybible_id>/', vote_views.vote_weeklybible, name='vote_weeklybible'),
    path('vote/research/<int:research_id>/', vote_views.vote_research, name='vote_research'),
    path('vote/customer/<int:customer_id>/', vote_views.vote_customer, name='vote_customer'),
    path('vote/activity/<int:activity_id>/', vote_views.vote_activity, name='vote_activity'),
    path('vote/gpt/<int:gpt_id>/', vote_views.vote_gpt, name='vote_gpt'),
    path('vote/gptanswer/<int:gptanswer_id>/', vote_views.vote_gptanswer, name='vote_gptanswer'),

    # weeklybible_views.py
    path('weeklybible/', weeklybible_views.weeklybible, name='weeklybible'),
    path('weeklybible/<int:weeklybible_id>/',
         weeklybible_views.weeklybible_detail, name='weeklybible_detail'),

    # research_views.py
    path('research/create/<int:weeklybible_id>/',
         research_views.research_create, name='research_create'),
    path('research/modify/<int:research_id>/',
         research_views.research_modify, name='research_modify'),
    path('research/delete/<int:research_id>/',
         research_views.research_delete, name='research_delete'),

    # customer_views.py
    path('customer/', customer_views.customer, name='customer'),
    path('customer/<int:customer_id>/',
         customer_views.customer_detail, name='customer_detail'),
    path('customer/create/',
         customer_views.customer_create, name='customer_create'),
    path('customer/modify/<int:customer_id>/',
         customer_views.customer_modify, name='customer_modify'),
    path('customer/delete/<int:customer_id>/',
         customer_views.customer_delete, name='customer_delete'),


    # activity_views.py
    path('activity/create/<int:customer_id>/',
         activity_views.activity_create, name='activity_create'),
    path('activity/modify/<int:activity_id>/',
         activity_views.activity_modify, name='activity_modify'),
    path('activity/delete/<int:activity_id>/',
         activity_views.activity_delete, name='activity_delete'),
]

neworld/views/activity_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import ActivityForm
from ..models import Customer, Activity



# Bulletin Board 답변등록
@login_required(login_url='common:login')
def activity_create(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    if request.method == "POST":
        form = ActivityForm(request.POST)
        if form.is_valid():
            activity = form.save(commit=False)
            activity.author = request.user
            activity.create_date = timezone.now()
            activity.customer = customer
            activity.save()
            return redirect('{}#activity_{}'.format(
                resolve_url('neworld:customer_detail', customer_id=customer.id), activity.id))
    else:
        form = ActivityForm()
    context = {'customer': customer, 'form': form}
    return render(request, 'neworld/customer_detail.html', context)


# Bulletin Board 답변 수정
@login_required(login_url='common:login')
def activity_modify(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    if request.user != activity.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('neworld:customer_detail', customer_id=activity.customer.id)
    if request.method == "POST":
        form = ActivityForm(request.POST, instance=activity)
        if form.is_valid():
            activity = form.save(commit=False)
            activity.modify_date = timezone.now()
            activity.save()
            return redirect('{}#activity_{}'.format(
                resolve_url('neworld:customer_detail', customer_id=activity.customer.id), activity.id))
    else:
        form = ActivityForm(instance=activity)
    context = {'activity': activity, 'form': form}
    return render(request, 'neworld/activity_form.html', context)


# Bulletin Board 답변 삭제
@login_required(login_url='common:login')
def activity_delete(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    if request.user != activity.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        activity.delete()
    return redirect('neworld:customer_detail', customer_id=activity.customer.id)

neworld/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer



# Bulletin Board 답변등록
@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('neworld:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'neworld/question_detail.html', context)


# Bulletin Board 답변 수정
@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('neworld:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('neworld:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'neworld/answer_form.html', context)


# Bulletin Board 답변 삭제
@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('neworld:detail', question_id=answer.question.id)

neworld/views/base_views.py
from django.shortcuts import render
from neworld.models import Scripture
from django.utils import timezone
from bs4 import BeautifulSoup
import logging
import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry
import datetime
from neworld.lib import get_number_of_week, date_range, date_range_for_crawling, get_day_of_week

logger = logging.getLogger('neworld')

# requests 세션 생성 (재시도 + 백오프)
session = requests.Session()
retry = Retry(connect=3, backoff_factor=0.5)
adapter = HTTPAdapter(max_retries=retry)
session.mount('https://', adapter)
session.mount('http://', adapter)

def index(request):
    logger.info("INFO 레벨로 출력")

    t_day = datetime.date.today()
    Today = str(t_day.year) + '-' + str(t_day.month).zfill(2) + '-' + str(t_day.day).zfill(2)
    seventhday = t_day + datetime.timedelta(7)
    Seventh_day = str(seventhday.year) + '-' + str(seventhday.month).zfill(2) + '-' + str(seventhday.day).zfill(2)

    # DB에 실제로 기록할 날짜 리스트
    date_range_RealDay = date_range(Today, Seventh_day)

    try:
        # 오늘 날짜의 성구가 이미 있는지 확인
        Scripture.objects.get(real_date=Today)
    except Scripture.DoesNotExist:
        # 오늘 데이터가 없으면 오늘부터 다시 크롤링
        d_week = []
        for i in range(len(date_range_RealDay)):
            crawl_day = t_day + datetime.timedelta(i + 1)
            url = 'https://wol.jw.org/ko/wol/h/r8/lp-ko/' + crawl_day.strftime('%Y/%m/%d')
            try:
                r = session.get(url, timeout=10)
                parser = BeautifulSoup(r.text, 'html.parser')
                scrip1 = parser.select_one('#dailyText > div.articlePositioner > div:nth-child(1) > p.themeScrp')
                body1 = parser.select_one('#dailyText > div.articlePositioner > div:nth-child(1) > div.bodyTxt > p.sb')
                scrip_text = scrip1.text if scrip1 else "데이터 준비 중"
                body_text = body1.text if body1 else "데이터 준비 중"
            except Exception as e:
                logger.error(f"크롤링 오류: {e}")
                scrip_text = "데이터 준비 중"
                body_text = "데이터 준비 중"

            target_day = t_day + datetime.timedelta(i)
            yyyy, mm, dd = target_day.year, target_day.month, target_day.day
            t_week = get_day_of_week(yyyy, mm, dd)
            d_week.append(t_week)

            scrt = Scripture(
                scripture=scrip_text,
                bodytext=body_text,
                real_date=date_range_RealDay[i],
                d_week=t_week,
                create_date=timezone.now()
            )
            scrt.save()

    # 오늘 날짜의 성구 가져오기
    scripture1 = Scripture.objects.get(real_date=Today)
    title = scripture1.real_date
    day_of_week = scripture1.d_week
    scripture = scripture1.scripture
    bodyText = scripture1.bodytext

    context = {
        'today_html': title,
        'day_of_week_html': day_of_week,
        'scripture_html': scripture,
        'bodyText_html': bodyText
    }
    return render(request, 'neworld/index.html', context)

neworld/views/goldmembership_views.py
from django.shortcuts import render

def goldmembership_guide(request):
    return render(request, 'neworld/goldmembership_guide.html')

neworld/views/permission_change.py
from neworld.models import Question, Answer, Meditation, Research
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

content_type = ContentType.objects.get_for_model(Question)
permission = Permission.objects.create(
    codename='can_change',
    name='Can Change Posts',
    content_type=content_type,
)

content_type = ContentType.objects.get_for_model(Answer)
permission = Permission.objects.create(
    codename='can_change',
    name='Can Change Posts',
    content_type=content_type,
)

content_type = ContentType.objects.get_for_model(Meditation)
permission = Permission.objects.create(
    codename='can_change',
    name='Can Change Posts',
    content_type=content_type,
)

content_type = ContentType.objects.get_for_model(Research)
permission = Permission.objects.create(
    codename='can_change',
    name='Can Change Posts',
    content_type=content_type,
)

templates/neworld/answer_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content"><strong>답변내용</strong></label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/neworld/comment_activity_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea></br>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/neworld/comment_research_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea></br>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/neworld/gpt_form_.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">글쓰기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div></br>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/neworld/question_detail.html
{% extends 'base.html' %}
{% load neworld_filter %}
{% block content %}
<div class="container my-3">
    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    {% if question.group.id in group_list %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-11"> <!-- 질문영역 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" >{{ question.content|mark }}</div>
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date %}
                        <div class="badge bg-light text-dark p-2 text-start mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge bg-light text-dark p-2 text-start">
                            <div class="mb-2">{{ question.author.first_name }}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>
                    <div class="my-3">
                        <a href="javascript:void(0)" data-uri="{% url 'neworld:vote_question' question.id  %}"
                            class="recommend btn btn-sm btn-outline-secondary"> 추천
                            <span class="badge rounded-pill bg-success">{{ question.voter.count }}</span>
                        </a>
                        {% if request.user == question.author %}
                        <a href="{% url 'neworld:question_modify' question.id  %}"
                            class="btn btn-sm btn-outline-secondary">수정</a>
                            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                                data-uri="{% url 'neworld:question_delete' question.id  %}">삭제</a>
                        {% endif %}
                    </div>
                    <!-- 질문 댓글 Start -->
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in question.comment_set.all %}  <!-- 등록한 댓글을 출력 -->
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">  <!-- 댓글 각각에 comment 스타일 지정 -->
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                              - {{ comment.author.first_name }}, {{ comment.create_date }}
                               {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'neworld:comment_modify_question' comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'neworld:comment_delete_question' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'neworld:comment_create_question' question.id  %}"
                           class="small"><small>댓글 추가 ..</small></a>  <!-- 댓글 추가 링크 -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-11">  <!-- 답변영역 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text">{{ answer.content|mark }}</div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge bg-light text-dark p-2 text-start mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge bg-light text-dark p-2 text-start">
                            <div class="mb-2">{{ answer.author.first_name }}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>
                    </div>
                    <div class="my-3">
                        <a href="javascript:void(0)" data-uri="{% url 'neworld:vote_answer' answer.id  %}"
                            class="recommend btn btn-sm btn-outline-secondary"> 추천
                            <span class="badge rounded-pill bg-success">{{ answer.voter.count }}</span>
                        </a>
                        {% if request.user == answer.author %}
                        <a href="{% url 'neworld:answer_modify' answer.id  %}"
                            class="btn btn-sm btn-outline-secondary">수정</a>
                            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                                data-uri="{% url 'neworld:answer_delete' answer.id  %}">삭제</a>
                        {% endif %}
                    </div>
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author.first_name }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'neworld:comment_modify_answer' comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'neworld:comment_delete_answer' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'neworld:comment_create_answer' answer.id  %}"
                           class="small"><small>댓글 추가 ..</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <a href="{% url 'neworld:question' %}" class="btn btn-primary" style="font-weight:bold"><i class="fas fa-list"></i>  목록으로</a>

    <form action="{% url 'neworld:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      name="content" id="content" class="form-control" rows="10"></textarea>
        </div></br>
        <input type="submit" value="답변등록" class="btn btn-primary" style="font-weight:bold">
    </form>
    {% endif %}
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(document).on('click', ".delete", function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(document).on('click', ".recommend", function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/neworld/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">글쓰기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div></br>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/neworld/research_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content"><strong>묵상 및 조사내용</strong></label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}