common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('password_reset/', views.MyPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('change_password/', views.change_password, name='change_password'),
    # path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),
]



# path('login/url/', views.RequestLoginViaUrlView.as_view(template_name='common/request_login_via_url_form.html'), name='request_login_via_url'),
# path('login/<uidb64>/<token>/', views.login_via_url, name='login_via_url'),

# path('activate/<uidb64>/<token>/', views.activate, name='activate'),

common/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.contrib.auth.models import Group
from django.core.mail import send_mail
# from django.contrib.auth.models import AbstractUser



# class User(AbstractUser):
#     username = models.CharField(db_index=True, unique=True, max_length=255)
#     first_name = models.CharField(max_length=150, null=True)
#     last_name = models.CharField(max_length=150, null=True)
#     nickname = models.CharField(max_length=150, null=True)
#     password = models.CharField(max_length=128, null=False)
#     is_superuser = models.BooleanField(null=True)
#     is_staff = models.BooleanField(null=True)
#     is_active = models.BooleanField(null=True)
#     email = models.EmailField(unique=True, blank=True)
#     last_login = models.DateTimeField(auto_created=True, null=True)
#     date_joined = models.DateTimeField(auto_created=True, null=True)
#     USERNAME_FIELD = 'email'
#     REQUIRED_FIELDS = ['username']


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(null=True, blank=True)
    website_url = models.URLField(null=True, blank=True)


def on_post_save_for_user(sender, **kwargs):
    if kwargs['created']:
        user = kwargs['instance']
        Profile.objects.create(user=user)

# User 회원 가입 시 Profile 생성하기
post_save.connect(on_post_save_for_user, sender=settings.AUTH_USER_MODEL)


# send_mail(
#     'Subject here',
#     'Here is the message.',
#     'neworld0@gmial.com',
#     ['neworld@me.com'],
#     fail_silently=False,
# )

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "password1", "password2", "email")


# class GroupForm(UserCreationForm):
#
#     class Meta:
#         model = Group
#         fields = '__all__'

# class UserForm(UserCreationForm):
#
#     class Meta:
#         model = User
#         fields = '__all__'


# from django.contrib.auth.forms import UserCreationForm
# from django.core.validators import validate_email
# from common.models import User
#
#
# class UserForm(UserCreationForm):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['username'].validators = [validate_email]
#         self.fields['username'].help_text = '이메일 형식을 입력하세요.'
#         self.fields['username'].label = 'Email'
#
#     def save(self, commit=True):
#         user = super().save(commit=False)
#         user.email = user.username
#         if commit:
#             user.save()
#         return user
#
#     class Meta(UserCreationForm.Meta):
#         model = User

common/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.views import PasswordChangeView, PasswordResetConfirmView, PasswordResetView
from django.shortcuts import render, redirect, resolve_url, HttpResponse, get_object_or_404
from django.views.generic import CreateView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
# from django.contrib.auth.hashers import check_password
# from django.contrib.auth import get_user_model
# from django.contrib import auth
# from django.contrib.sites.shortcuts import get_current_site
# from django.template.loader import render_to_string
# from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
# from django.utils.encoding import force_bytes
# from django.core.mail import EmailMessage
# from django.utils.encoding import force_bytes, force_text
# from django.utils import timezone
# from django.core.exceptions import ValidationError
# from django.contrib.auth.tokens import default_token_generator
# from django.http import Http404

from common.forms import UserForm
from config.settings import base
from common.models import Profile
from common.decorators import unauthenticated_user, allowed_users, son123_only
# from common.tokens import account_activation_token


@login_required(login_url='common:login')
def profile(request, user_id):
    user = User.objects.get(id=user_id)
    groups = user.groups.all()
    context = {'groups': groups}
    return render(request, 'common/profile.html', context)


# 계정 생성
# @unauthenticated_user
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)   # 사용자 인증
            # group = Group.objects.get(name='321son')
            # user.groups.add(group)
            # messages.success(request, 'Account was created for ' + username)
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


def page_not_found(request, exception):
    """
    404 Page not found
    """
    return render(request, 'common/404.html', {})


def internal_server_error(request, *args, **argv):
    """
    500 Internal Server Error
    """
    return render(request, 'common/500.html', status=500)


# class MyPasswordChangeView(PasswordChangeView):
#     success_url = reverse_lazy('common:profile')
#     template_name = 'common/password_change_form.html'
#
#     def form_valid(self, form):
#         messages.info(self.request, '암호 변경을 완료했습니다.')
#         return super().form_valid(form)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'common/change_password.html', {
        'form': form
    })

class MyPasswordResetView(PasswordResetView):
    success_url = reverse_lazy('common:login')
    template_name = 'common/password_reset_form.html'
    email_template_name = 'common/password_reset.html'

    def form_valid(self, form):
        messages.info(self.request, '암호 변경 메일을 발송했습니다.')
        return super().form_valid(form)


class MyPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy('common:login')
    template_name = 'common/password_reset_confirm.html'

    def form_valid(self, form):
        messages.info(self.request, '암호 초기화를 완료했습니다.')
        return super().form_valid(form)


# class SignupView(CreateView):
#     model = User
#     form_class = UserForm
#     template_name = 'common/signup.html'
#
#     def get_success_url(self):
#         next_url = self.request.GET.get('next') or 'profile'
#         return resolve_url(next_url)
#
#     def form_valid(self, form):
#         user = form.save()
#         login(self.request, user)
#         return redirect(self.get_success_url())
#
# signup = SignupView.as_view()


# class RequestLoginViaUrlView(PasswordResetView):
#     template_name = 'common/request_login_via_url_form.html'
#     title = '이메일을 통한 로그인'
#     email_template_name = 'common/login_via_url.html'
#     success_url = base.LOGIN_REDIRECT_URL
#
#
# def login_via_url(request, uidb64, token):
#     User = get_user_model()
#     try:
#         uid = urlsafe_base64_decode(uidb64).decode()
#         current_user = User.objects.get(pk=uid)
#     except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
#         raise Http404
#
#     if default_token_generator.check_token(current_user, token):
#         login(request, current_user)
#         messages.info(request, '로그인이 승인되었습니다.')
#         return redirect('neworld:index')
#
#     messages.error(request, '로그인이 거부되었습니다.')
#     return redirect('neworld:index')
#
#
#
# def signup(request):
#     if request.method == "POST":
#         if request.POST["password1"] == request.POST["password2"]:
#             user = User.objects.create_user(
#                 username=request.POST["username"],
#                 password=request.POST["password1"],
#                 first_name=request.POST['first_name'],
#                 last_name=request.POST['last_name'],
#                 nickname=request.POST['nickname'])
#             user.is_active = False
#             user.is_superuser = False
#             user.is_staff = False
#             user.save()
#             current_site = get_current_site(request)
#             # localhost:8000
#             message = render_to_string('common/user_activate_email.html', {
#                 'user': user,
#                 'domain': current_site.domain,
#                 'uid': urlsafe_base64_encode(force_bytes(user.pk)).encode().decode(),
#                 'token': account_activation_token.make_token(user),
#             })
#             mail_subject = "[SOT] 회원가입 인증 메일입니다."
#             user_email = user.email
#             email = EmailMessage(mail_subject, message, to=[user_email])
#             email.send()
#             return HttpResponse(
#                 '<div style="font-size: 40px; width: 100%; height:100%; display:flex; text-align:center; '
#                 'justify-content: center; align-items: center;">'
#                 '입력하신 이메일<span>로 인증 링크가 전송되었습니다.</span>'
#                 '</div>'
#             )
#         return redirect('neworld:index')
#     else:
#         form = UserForm()
#         return render(request, 'common/signup_test.html', {'form': form})
#
#
#
# def activate(request, uid64, token):
#
#     uid = force_text(urlsafe_base64_decode(uid64))
#     user = User.objects.get(pk=uid)
#
#     if user is not None and account_activation_token.check_token(user, token):
#         user.is_active = True
#         user.date_joined = timezone.now()
#         user.save()
#         login(request, user)
#         return redirect('neworld:index')
#     else:
#         return HttpResponse('비정상적인 접근입니다.')

templates/common/activate_dummy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello, Neworld!</title>
</head>
<body>
    <h1>Hello, Neworld!</h1>
</body>
</html>

templates/common/change_password.html
{% extends "base.html" %}

{% block content %}
    <h2 class="m-3 p-3" style="text-align:center;">비밀번호 변경</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="card m-3 p-3">
            <table>
                {{ form }}
            </table>
            <div class="col-12 text-center p-3 m-3">
                <button type="submit">제출</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/common/login_test.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
            <div class="col-4">
                <a href="{% url 'common:request_login_via_url' %}"><strong>이메일로 로그인</strong></a>
            </div>
        <div class="col-4 text-right">
            <span>또는 <a href="{% url 'common:signup' %}"><strong>계정 생성</strong></a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID(이메일 형식)</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
    <div class="col-12 text-right">
        <a href="{% url 'common:password_reset' %}"><strong>암호 초기화</strong></a>
    </div>
</div>
{% endblock %}

templates/common/login_via_url.html
{% autoescape off %}

아래 주소를 통해 {{ site_name }}에 로그인하실 수 있습니다.

링크: {{ protocol }}://{{ domain }}{% url "login_via_url" uidb64=uid token=token %}

{% endautoescape %}

templates/common/password_change_form.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
    <div class="pt-3">
        <p class="pt-3"></p>
        <p class="pt-3"></p>
    </div>
</div>
<h2>암호변경</h2>
<form action="" method="post">
    {% csrf_token %}
    <div class="card m-2 p-2">
        <table>
            {{ form.as_table }}
        </table>
        <div class="col-8 text-right">
            <input type="submit">
        </div>
    </div>
</form>
{% endblock %}

templates/common/password_reset.html
아래 주소를 통해 {{ site_name }}에 접속하여 비밀번호를 초기화 할 수 있습니다.

링크: {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

templates/common/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
    <p>암호 초기화 성공</p>
{% endblock %}

templates/common/password_reset_form.html
{% extends "base.html" %}

{% block content %}
    <h2>암호 리셋</h2>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <div class="col-8 text-right">
            <input type="submit">
        </div>
    </form>
{% endblock %}

templates/common/profile.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <h3>{{ user.username }}'s Profile </h3>
    <div class="card my-3 p-3">
        <div class="card my-3 p-3">
            <h4>이름: {{ user.first_name|default:"&dash;" }} </h4>
        </div>
        <div class="card my-3 p-3">
            <h4>별명: {{ user.last_name|default:"&dash;" }} </h4>
        </div>
        <div class="card my-3 p-3">
            <h4>이메일: {{ user.email|default:"&dash;" }} </h4>
        </div>
        <div class="card my-3 p-3">
            <h4>그룹: {% for group in groups %} [ {{ group|default:"&dash;" }} ] {% endfor %}</h4>
        </div>
    </div>
    <div class="col-12 text-right">
        <a href="{% url 'common:change_password' %}">비밀번호 변경하기</a>
    </div>
</div>
{% endblock %}

templates/common/request_login_via_url_form.html
{% extends "base.html" %}

{% block content %}
<div class="container my-3">
    <div class="row my-4">
        <div class="col-6">
            <h4>이메일로 로그인</h4>
        </div>
        <div class="col-6">
            <a href="{% url 'common:login' %}"><strong>아이디로 로그인</strong></a>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:request_login_via_url' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="my-4">
            <button type="submit" class="btn btn-primary">로그인</button>
        </div>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4><strong>계정생성</strong></h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}"><strong>로그인 하세요.</strong></a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 아이디</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="first_name">사용자 이름</label>
            <input type="text" class="form-control" name="first_name" id="first_name"
                   value="{{ form.first_name.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="last_name">별명</label>
            <input type="text" class="form-control" name="last_name" id="last_name"
                   value="{{ form.last_name.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}"></br>
        </div>
<!--        <div class="form-group">-->
<!--            <h6>그룹 선택</h6>-->
<!--            <div class="card">-->
<!--                <div class="form-check m-2">-->
<!--                <input class="form-check-input" type="radio" name="groups" id="groups1"-->
<!--                       value="{{ form.groups.value|default_if_none:'' }}">-->
<!--                <label class="form-check-label px-2" for="groups1">321son</label>-->
<!--                </div>-->
<!--                <div class="form-check m-2">-->
<!--                <input class="form-check-input" type="radio" name="groups" id="groups2"-->
<!--                       value="{{ form.groups.value|default_if_none:'' }}">-->
<!--                <label class="form-check-label px-2" for="groups2">Lee's Family</label>-->
<!--                </div>-->
<!--                <div class="form-check m-2">-->
<!--                <input class="form-check-input" type="radio" name="groups" id="groups3"-->
<!--                       value="{{ form.groups.value|default_if_none:'' }}">-->
<!--                <label class="form-check-label px-2" for="groups3">Son's Family</label>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}

templates/common/signup_old.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4><strong>계정생성</strong></h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}"><strong>로그인 하세요.</strong></a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 아이디</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="first_name">사용자 이름</label>
            <input type="text" class="form-control" name="first_name" id="first_name"
                   value="{{ form.first_name.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="last_name">별명</label>
            <input type="text" class="form-control" name="last_name" id="last_name"
                   value="{{ form.last_name.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}

templates/common/signup_test.html
{% extends "base.html" %}

{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4><strong>계정생성</strong></h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}"><strong>로그인 하세요.</strong></a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 아이디(이메일 형식)</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="last_name">사용자 성명(성)</label>
            <input type="text" class="form-control" name="last_name" id="last_name"
                   value="{{ form.last_name.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="first_name">사용자 성명(이름)</label>
            <input type="text" class="form-control" name="first_name" id="first_name"
                   value="{{ form.first_name.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="nickname">별명</label>
            <input type="text" class="form-control" name="nickname" id="nickname"
                   value="{{ form.nickname.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
<!--        <div class="form-group">-->
<!--            <label for="email">이메일</label>-->
<!--            <input type="text" class="form-control" name="email" id="email"-->
<!--                   value="{{ form.email.value|default_if_none:'' }}">-->
<!--        </div>-->
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}

templates/common/user_activate_email.html
{% autoescape off %}
    안녕하세요

    아래 링크를 클릭하면 회원가입 인증이 완료됩니다.

    회원가입 링크 : http://{{ domain }}{% url 'common:activate' uid64=uid token=token %}

{% endautoescape %}